# Generated by Django 3.1.5 on 2021-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0003_auto_20210221_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
