# Generated by Django 3.1.5 on 2021-02-20 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='id',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
    ]
