# Generated by Django 3.1.5 on 2021-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at'),
        ),
    ]
